# Generated by Django 6.0.5 on 2026-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0008_alter_person_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="foo",
            field=models.IntegerField(null=True),
        ),
    ]
